#+title: Zsh config directory
This is a possibly futile attempt to establish some modularity and organization to my zsh
configuration. Hold onto your butts.

The files herein are sourced via a zsh ~for~ loop over a glob; in most cases, the load order
doesn't matter—or at least /shouldn't/ matter—but not all dependencies can be removed
without undue hassle. Thus, files are named according to a system which uses numerical
prefixes to make the order somewhat predictable.

* the filenaming system
In general, more "fundamental" things are loaded earlier; there's a halfbaked notion that
00s-50s are more concerned with setting up tools and features, while 60s-90s are
availabile to build on that foundation by defining aliases, "I just opened a terminal"
side-effects, and personal BS. The categories are outlined in a bit more detail below:

- 00-* :: configure zsh features
- 10-* :: non-zsh-specific POSIX setup
- 20-* :: common/foundational POSIX/CLI tools
- 30-* :: other CLI tools
- 40-* :: programming languages and tooling
- 50-* :: personal tools and meta-config
- 60-* :: GUI programs
- 80-* :: personal stuff, shenanigans, aliases, etc
- 90-* :: computer-specific stuff, not to be tracked under git
- maybe/* :: conditional configuration (see below)

In general, these files shouldn't imperatively trigger user-visible "on-load" side-effects
themselves, just silently configure the environment. When you do want such side-effects,
silently configure the environment to contain a function which does trigger them and
arrange for =.zshrc= call it.

* conditional configuration
Files with config that should only be sourced under certain conditions should be placed in
the =maybe/= subdirectory; evaluating those conditions and sourcing the corresponding files
should be done manually, explicitly, and individually in =.zshrc=.
