#!/bin/bash

case $1 in
  --with-sway) sudo pacman -S --noconfirm --needed - < $HOME/lib/eos-sway-packages ;;
esac

sudo pacman -S --noconfirm --needed - < $HOME/lib/arch-deps

yay -S --noconfirm --needed - < $HOME/lib/aur-deps
