#!/bin/bash

enable_copr_repos () {
  local state_file="$HOME/.local/state/dots-copr-repos.last-synced"
  local busted_cache
  if [ ! -f "$state_file" ]; then
    busted_cache=true
  elif [ "$(date -r ~/lib/copr-repos +%s)" -gt "$(date -f "$state_file" +%s)" ]; then
    busted_cache=true
  fi

  if [ -n "$busted_cache" ]; then
    while read -r repo; do
      sudo dnf -y copr enable "$repo"
    done < ~/lib/copr-repos
    date > "$state_file"
  fi
}

enable_third_party_rpm_repos () {
  local state_file="$HOME/.local/state/dots-rpm-repos.last-synced"
  local busted_cache
  if [ ! -f "$state_file" ]; then
    busted_cache=true
  elif [ "$(date -r ~/lib/rpm-repos.sh +%s)" -gt "$(date -f "$state_file" +%s)" ]; then
    busted_cache=true
  fi

  if [ -n "$busted_cache" ]; then
    sh ~/lib/rpm-repos.sh
    date > "$state_file"
  fi
}

main () {
  local args=("$@")
  local should_install_copr=true
  local should_install_third_party_rpms=true
  local deps=()

  # Add unconditional deps to array.
  while read -r dep; do
    deps+=("$dep")
  done < ~/lib/fedora-deps

  for ((i=0; i<"${#args[@]}"; i++)); do
    local arg="${args[i]}"

    case $arg in
      --without-copr|--no-coprs|--no-copr)
        unset should_install_copr
        ;;
      --without-rpm-repos|--no-rpm-repos|--no-rpms|--no-rpm)
        unset should_install_third_party_rpms
        ;;
    esac
  done

  # Add conditional deps to array. Maybe.
  if [ -n "$should_install_copr" ]; then
    enable_copr_repos

    while read -r dep; do
      deps+=("$dep")
    done < ~/lib/copr-deps
  fi

  if [ -n "$should_install_third_party_rpms" ]; then
    enable_third_party_rpm_repos

    while read -r dep; do
      deps+=("$dep")
    done < ~/lib/rpm-deps
  fi

  # hold onto your butts
  sudo dnf install "${deps[@]}"
}

main "$@"
