#+title: Hyprland config

This file is the source of truth; let's make it easy to work with:
#+begin_src elisp :tangle no :results none
(org-babel-tangle-file (buffer-file-name))
#+end_src

Now then.

#+begin_quote
Hyprland, light of my wayland, fire of my =r/unixporn=. My crutch, my compositor.
Hy-pr-land: the tip of the tongue taking a trip of three steps down the palate to tap, at
"d", on the teeth.
#+end_quote

* how to configure you a hyprland
For all categories, see https://wiki.hyprland.org/Configuring/Variables/.

** split config into multiple files
#+begin_src conf :tangle no
source = ~/.config/hypr/some-file.conf
#+end_src

** window rules
See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
#+begin_src conf
windowrule = float, ^(kitty)$
windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
#+end_src

** per-device config
Here's an example (which won't be added to the actual config):
#+begin_src conf :tangle no
device:epic mouse V1 {
    sensitivity = -0.5
}

#+end_src

* monitor setup
See https://wiki.hyprland.org/Configuring/Monitors/
#+begin_src conf :tangle hyprland.conf
monitor=,preferred,auto,auto

#+end_src

* make it pretty
** decoration
#+begin_src conf :tangle hyprland.conf
general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 3
    gaps_out = 3
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 3
    blur = yes
    blur_size = 3
    blur_passes = 1
    blur_new_optimizations = on

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

#+end_src
** animations
#+begin_src conf :tangle hyprland.conf
animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

#+end_src
* input
#+begin_src conf :tangle hyprland.conf
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
        tap-to-click = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = on
    workspace_swipe_invert = false
}

#+end_src

* layouts
    See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ and https://wiki.hyprland.org/Configuring/Master-Layout/  for more

#+begin_src conf :tangle hyprland.conf
dwindle {
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this

    no_gaps_when_only = yes
}

master {
    new_is_master = true
}

#+end_src

* keybinds
** define ~$mainMod~
#+begin_src conf :tangle hyprland.conf
$mainMod = SUPER

#+end_src

** global window management actions
#+begin_src conf :tangle hyprland.conf
bind = $mainMod, Q, killactive,
bind = $mainMod, E, exit,
bind = $mainMod, V, togglefloating,
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, s, togglesplit, # dwindle
bind = $mainMod, F, fullscreen

bind = $mainMod SHIFT, T, swapactiveworkspaces
#+end_src

** function keys
keyboard backlight
#+begin_src conf :tangle hyprland.conf
bindle =, XF86MonBrightnessUp, exec, brightnessctl set +5% && notify-send "Brightness - $(brightnessctl get)%"
bindle =, XF86MonBrightnessDown, exec, brightnessctl set 5%- && notify-send "Brightness - $(brightnessctl get)%"

bindle = , XF86LaunchA, exec, ~/bin/kbd-light-down
bindle = , XF86Search, exec, ~/bin/kbd-light-up
#+end_src

** open key apps
#+begin_src conf :tangle hyprland.conf
bind = $mainMod, return, exec, kitty
# bind = $mainMod, F, exec, thunar
bind = $mainMod SHIFT, F, exec, dolphin
bind = $mainMod, D, exec, wofi --show drun

#+end_src
** navigation
#+begin_src conf :tangle hyprland.conf
bind = $mainMod, left, movefocus, l
bind = $mainMod, h, movefocus, l
bind = $mainMod, down, movefocus, d
bind = $mainMod, j, movefocus, d
bind = $mainMod, up, movefocus, u
bind = $mainMod, k, movefocus, u
bind = $mainMod, right, movefocus, r
bind = $mainMod, l, movefocus, r

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

#+end_src
** moving windows
#+begin_src conf :tangle hyprland.conf
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, down, movewindow, d
bind = $mainMod SHIFT, j, movewindow, d
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, l, movewindow, r

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

#+end_src
** mouse/trackpad events
#+begin_src conf :tangle hyprland.conf
# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

#+end_src

** laptop/hardware interactions
These are inherently device-specific. Run
#+begin_src shell :tangle no
hyprctl devices
#+end_src
and scroll down to the "Switches" section for the name of the lid switch. Use that. It
might have a ridiculous name!

#+begin_src conf :tangle (if (string-equal "Apple SMC power\n" (shell-command-to-string "hyprctl devices | grep -o 'Apple SMC power'")) "hyprland.conf" "no")
bind = , switch:Apple SMC power/lid events, exec, swaylock -i ~/Pictures/crescent-pluto.jpg
#+end_src

#+begin_src conf :tangle (if (string-equal "Lid Switch\n" (shell-command-to-string "hyprctl devices | grep -o 'Lid Switch'")) "hyprland.conf" "no")
bind = , switch:Lid Switch, exec, swaylock -i ~/Pictures/crescent-pluto.jpg
#+end_src

* startup things
#+begin_src conf :tangle hyprland.conf
exec-once = eww --restart open bar
exec-once = swaybg -i /home/amb/Pictures/crescent-pluto.jpg
exec-once = dunst
#+end_src

* notes
** missing keybinds [1/7]
- [X] brightness up/down
- [ ] volume up/down and mute
- [ ] keyboard backlight up/down
Bind to the keys next to the monitor brightness ones: expose and searchyboi
- [ ] toggle fullscreen
- [ ] media control buttons
- [ ] pop open floating terminal
- [ ] move windows
