#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot -z $PICTURE"

BLUR="5x4"

$SCREENSHOT
convert $PICTURE -blur $BLUR $PICTURE
# TODO install i3lock-color and style the indicator to not use that garish green and red
i3lock -i $PICTURE
rm $PICTURE
